net-im/libsignal-node: Fix build with rust 1.71.0
Do not abort if documentation is missing as we don't need it.

error: missing documentation for an extern crate
--> curve25519-dalek-4f0aa6653c51598daa0a2f53b8ba54ce0eedfbdd/src/lib.rs:265:1
265 | pub extern crate digest;
    | ^^^^^^^^^^^^^^^^^^^^^^^

PR:		272449